name: flutter_platform_alert
description: A plugin helps to call native API to play alert sound and show alert dialogs. For example, it bridges MessageBox and TaskDialogIndirect on Windows.
version: 0.5.3
homepage: https://github.com/zonble/flutter_platform_alert

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0 <5.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: net.zonble.flutter_platform_alert
        pluginClass: FlutterPlatformAlertPlugin
      ios:
        pluginClass: FlutterPlatformAlertPlugin
      macos:
        pluginClass: FlutterPlatformAlertPlugin
      windows:
        pluginClass: FlutterPlatformAlertPlugin
      linux:
        pluginClass: FlutterPlatformAlertPlugin

screenshots:
  - description: "flutter_platform_alert on Android"
    path: screenshot_android.png
  - description: "flutter_platform_alert on iOS"
    path: screenshot_ios.png
  - description: "flutter_platform_alert sheet on iOS"
    path: screenshot_ios_sheet.png
  - description: "flutter_platform_alert on Linux."
    path: screenshot_linux.png
  - description: "flutter_platform_alert on macOS."
    path: screenshot_macos.png
  - description: "flutter_platform_alert on Windows."
    path: screenshot_windows.png
  - description: "flutter_platform_alert on Windows 11."
    path: screenshot_windows_11.png
